name: remote ssh command
on: 
  push: 
    branches:
      [main]
    
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Deploy Files
      uses: appleboy/scp-action@master
      with:
        host: ec2-174-129-44-24.compute-1.amazonaws.com
        username: ec2-user
        key: ${{ secrets.RSA_PRIVATE_KEY }}
        port: 22
      
